[package]
name = "emulator"
version = "0.1.0"
authors = ["Alexis Boisserand <APB14@acuitysso.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
num-traits = "0.2"
num-derive = "0.3"